server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pcquotation?useSSL=false&serverTimezone=UTC
    username: root
    password: "0000"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
openapi:
  url: http://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=
  authentication-key:
    encoding: N08vvp1vbGXKB0dFb1s3hqd3WhZdyFk7FrIcHut2YXgnBfZpo9ByLIzoK5Xf9%2BrzfW%2FRE%2BV0ScEfXtFSvxDoLg%3D%3D
    decoding: N08vvp1vbGXKB0dFb1s3hqd3WhZdyFk7FrIcHut2YXgnBfZpo9ByLIzoK5Xf9+rzfW/RE+V0ScEfXtFSvxDoLg==
jwt:
  secretKey: nnqDC5CWSCpAE3JvJLAj40O87klnbNj9